#!/usr/bin/env python3

from datetime import datetime
from string import printable
from subprocess import run
from difflib import ndiff
from os import geteuid
from time import sleep
from sys import stdout
from sys import argv
from os import fsync
from os import sync

# How long to wait between device queries, in seconds
# 0.1 is a pretty sane default
delay = 0.1

usbvm = "sys-usb" # The UsbVM to query devices on

# The panic command to trigger when a device change is detected
panic_command = ["/usr/sbin/poweroff", "-p", "-f"] # Force immediate poweroff

# Write logs to this file. Useful for knowing whether a USB panic was triggered
# vs whether your device shutdown for some other reason (kernel panic? crash?)
log_file = "/var/log/qusbkill.log" # Set to None or "" to disable logging

# Sync disk before poweroff? This can potentially prevent data loss
# Although unsaved data will still be lost
# If this script is set to write logs, the log will be synced even if this is False
do_sync = False

if geteuid() != 0:
	run(["sudo"] + argv)
	raise SystemExit

# The command to use to query USB devices. Do not change this unless you know what you're doing
lsusb = ["/usr/bin/qvm-run", "-u", "root", "--pass-io", usbvm, "lsusb"]

def clean(string):
	return ''.join([c for c in string if c in printable])
def write(f, w):
	f.write(w)
	stdout.write(w)
	f.flush()
	fsync(f)
def diff(a, b):
	return ''.join([c[2] for c in ndiff(a, b) if c[0] != " "])

log = None
if log_file != None and log_file != "":
	log = open(log_file, "a")
	write(log, "qusbkill: starting @ %s\n" %(datetime.now().isoformat()))

try:
	expected_devices = run(lsusb, capture_output=True).stdout.decode()
	print("Monitoring USB device changes...")
	while True:
		usb_devices = run(lsusb, capture_output=True).stdout.decode()
		if usb_devices != expected_devices:
			print("Device change detected")
			if log != None:
				write(log, "%s\nqusbkill: triggered panic @ %s\nexpected:\n%s\ndetected:\n%s\nchanged device:\n%s\n\n" %("-" * 64, datetime.now().isoformat(), clean(expected_devices), clean(usb_devices), clean(diff(expected_devices, usb_devices))))
			if do_sync:
				sync()
				write(log, "-- Synced --\n")
			run(panic_command)
			expected_devices = usb_devices
		sleep(delay)
except KeyboardInterrupt:
	print("Caught ctrl+c, quitting...")
except SystemExit:
	print("Caught exit signal, quitting...")
if log != None:
	write(log, "%s\nqusbkill: gracefully shutting down @ %s\n" %("-" * 64, datetime.now().isoformat()))
	log.close()
